### ISSUE TITLE
Juurastendamine vaja panna frontendi koos tärniga ülesannetega

### ISSUE THREAD

**Issue by AstrayJ** [hermannkabi/pranglimisrakendus#17]
Lisaks, kui saab, panna juurimisel ümardamine kuni 4 kohani, muidu saab panna paljude vastuseks 0.

**Comment by hermannkabi** [comment]
See on tehtud, aga täisarvudega on paar probleemi:
1) Juurimise vastus on definitsiooni kohaselt positiivne, aga täisarvudes tuleb pooltel kordadel ka negatiivne vastus
2) Teine tase täisarvudega juurimises tagastab ülikeerulisi tehteid, vt pilti.
3) Astejuurimisel tekib naturaalarvudega ikka veel juured 0 ja 1.
4) Astejuurimisel täisarvudega tekib mingi veider viga.

![image](https://github.com/hermannkabi/pranglimisrakendus/assets/63232411/960a48f4-6311-4702-839b-4e563b8d3e4d)

**Comment by AstrayJ** [comment]
Vaata üle täisarvudega juurimine - on vaja luua harilike murdudena. Või sobib ka nii?

![image_2024-02-20_222439502](https://github.com/hermannkabi/pranglimisrakendus/assets/131436862/a276b1f5-f896-443d-bd1e-318f2a908502)

**Comment by hermannkabi** [comment]
Murruna näitamine on kindlasti parem. Kardan juba seda ülesannet, aga proovin kuidagi hakkama saada :)

Mida ma tähele panin on see, et mõnikord tuleb juurimise vastus negatiivne (üsna harva, aga siiski). Naturaalarvudega seda probleemi _vist_ ei ole.
