### ISSUE TITLE
Võrdlemine tagastab tühja loendi

### ISSUE THREAD

**Issue by hermannkabi** [hermannkabi/pranglimisrakendus#4]
Tasemetest sõltumata tagastab võrdlemine tühja loendi.

**Comment by AstrayJ** [comment]
Võrdlemine peaaegu valmis.

Vaja 3. tasemega tegeleda ja luua frontendi väljund.

**Comment by hermannkabi** [comment]
3. taseme võrdlemine ei arvuta avaldise väärtust korralikult. Nt allolev pilt:

![image](https://github.com/hermannkabi/pranglimisrakendus/assets/63232411/27cc8567-9222-467d-9405-87dd23951b2a)

Samuti oleks vaja tase lisada tehtele (peaks lihtne olema). 

Front endi pool (punktid, pärastine vaade jne) on valmis.
